config/routes.rb
OpenStreetArt::Application.routes.draw do

  resources :spots do
    collection do
      post 'remote_create'
    end
  end
  

  devise_for :users

  root :to => 'home#index'

end

app/models/spot.rb
class Spot < ActiveRecord::Base
  attr_accessible :content, :lat, :lng, :spot_type, :main_image
  
  has_attached_file :main_image, :styles => { :small => "150x150>", :small_fix => "70x70#", :normal => "600x350#" }

  validates_attachment_size :main_image, :less_than => 5.megabytes
  validates_attachment_content_type :main_image, :content_type => ['image/jpeg', 'image/png']

  validates_presence_of :lat
  validates_presence_of :lng
  validates_presence_of :content
  validates_presence_of :main_image

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @markers = Spot.all
  end

  def about
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController

  skip_before_filter :verify_authenticity_token, :only => 'remote_create'

  # GET /spots
  # GET /spots.json
  def index
    @spots = Spot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spots }
    end
  end

  # GET /spots/1
  # GET /spots/1.json
  def show
    @spot = Spot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spot }
    end
  end

  # GET /spots/new
  # GET /spots/new.json
  def new
    @spot = Spot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spot }
    end
  end

  # GET /spots/1/edit
  def edit
    @spot = Spot.find(params[:id])
  end


  def remote_create
    puts "a"*99
    
    data = StringIO.new(Base64.decode64(params[:spot][:main_image_base64]))
    data.class.class_eval { attr_accessor :original_filename, :content_type }
    data.original_filename = "sc.png"
    data.content_type = "image/png"

    params[:spot].delete :main_image_base64
    

    @spot = Spot.new(params[:spot])
    @spot.main_image = data
    
    puts @spot
    if @spot.save
      puts "Success"
      render :json => {:success => true}
    else
      render :json => {:success => false}
    end
  end

  # POST /spots
  # POST /spots.json
  def create
    @spot = Spot.new(params[:spot])
    
    respond_to do |format|
      if @spot.save
        format.html { redirect_to @spot, notice: 'Spot was successfully created.' }
        format.json { render json: @spot, status: :created, location: @spot }
      else
        format.html { render action: "new" }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /spots/1
  # PUT /spots/1.json
  def update
    @spot = Spot.find(params[:id])

    respond_to do |format|
      if @spot.update_attributes(params[:spot])
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy

    respond_to do |format|
      format.html { redirect_to spots_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<%= content_for :javascripts do %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
<% end %>

<script>
  function AddDynamicMarkers() {
  <% @markers.each do |m| %>
    map.addMarker({
//    animation : google.maps.Animation.BOUNCE, 
    lat: <%= m.lat %>,
    lng: <%= m.lng %>,
    details : <%= m.id %>,
    infoWindow: {
    content: '<%= image_tag m.main_image(:normal) %><br/><center>par <%= m.author %></center>'
    }
    });
  <% end %>
  }
</script>


<!-- Main page start -->

<div class="vertical-text bottom-text">
  OpenStreetMap
</div>


<div id="main-page">

  <div id="sidenav">
    
    <ul>
      <li class="active">
	<%= image_tag 'home.png', :width => '50' %>
	<small>HOME</small>
      </li>
    </ul>

  </div>

  <div id="sidebar">
    <ul>

      <% @markers.each do |m| %>
	<% if m.main_image.exists? %>
	  <li data-lng="<%= m.lng %>" 
	      data-lat="<%= m.lat %>"
	      data-id="<%= m.id %>"
	      class="spots">
	    <span class="mini-image-prev">
	      <%= image_tag m.main_image(:small_fix) %>
	    </span>
	    <span class="arrondissement-prev">
	      Paris
	    </span>
	  </li>
	<% end %>
      <% end %>
    </ul>
  </div>


  <div id="map-part">

    <div id="map-top">
      <ul>
	<li id="set-center">
	  RESET Map
	</li>
	<li>

	  <div id="switch-sound">
	    Stop sound
      	  </div>

	  <audio autoplay loop id="background-sound" volume="1" style="display:none">
      	    <source src="/3902.mp3" type="audio/mpeg" />
      	    <source src="/3902.ogg" type="audio/ogg" />
      	    Your browser does not support the audio tag.
      	  </audio>	  
	</li>

	<li id="launch-exploration">
	  Lancer l'exploration
	</li>

	<li id="register">
	  <%= image_tag 'login2.png', :height => '11' %>
	  <% if user_signed_in? %>
	    <%= current_user.email %> <%= link_to 'Logout', destroy_user_session_path  %>	    
	  <% else %>
	    <%= link_to 'S\'enregister', new_user_session_path, :method => :delete  %>
	  <% end %>
	</li>
      </ul>
    </div>

    <div id="map">
    </div>

  </div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenStreetArt</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Niconne' rel='stylesheet' type='text/css'>
  </head>
  <body>

    <%= yield %>

  </body>
  <%= yield :javascripts %>
  <%= javascript_include_tag :application %>


  <% if Rails.env.production? -%>
    <script>
      var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']];
      (function(d, t) {
      var g = d.createElement(t),
      s = d.getElementsByTagName(t)[0];
      g.async = true;
      g.src = ('https:' == location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      s.parentNode.insertBefore(g, s);
      })(document, 'script');
    </script>
  <%- end -%>

</html>

app/views/spots/_form.html.erb
<%= semantic_form_for @spot do |f| %>
  <%= f.inputs :lat, :lng, :spot_type, :content, :main_image %>
  <%= f.submit %>
<% end %>

app/views/spots/edit.html.erb
<h1>Editing spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @spot %> |
<%= link_to 'Back', spots_path %>

app/views/spots/index.html.erb
<h1>Listing spots</h1>

<table>
  <tr>
    <th>Lat</th>
    <th>Lng</th>
    <th>Spot type</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spots.each do |spot| %>
  <tr>
    <td><%= spot.lat %></td>
    <td><%= spot.lng %></td>
    <td><%= spot.spot_type %></td>
    <td><%= spot.content %></td>
    <td><%= link_to 'Show', spot %></td>
    <td><%= link_to 'Edit', edit_spot_path(spot) %></td>
    <td><%= link_to 'Destroy', spot, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Spot', new_spot_path %>

app/views/spots/new.html.erb
<h1>New spot</h1>

<%= render 'form' %>

<%= link_to 'Back', spots_path %>

app/views/spots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lat:</b>
  <%= @spot.lat %>
</p>

<p>
  <b>Lng:</b>
  <%= @spot.lng %>
</p>

<p>
  <b>Spot type:</b>
  <%= @spot.spot_type %>
</p>

<p>
  <b>Content:</b>
  <%= @spot.content %>
</p>


<%= link_to 'Edit', edit_spot_path(@spot) %> |
<%= link_to 'Back', spots_path %>